CREATE DATABASE examen;
USE examen;
CREATE TABLE client (
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    company VARCHAR(255) NOT NULL,
    note VARCHAR(255)
);